language: python
python:
    - "3.7"
    - "pypy"
install:
    - pip install -r requirements.txt --use-mirrors
script:
    - nosetests --with-coverage --cover-package=overlay_parse
after_success:
  - coveralls
dist: xenial
notifications:
  email:
    recipients:
      - cperivol@csail.mit.edu

    on_success: always
    on_failure: always
